spring.application.name=medi-track

telegram.bot.username=@medi_track_bot

spring.datasource.url=jdbc:postgresql://localhost:5432/medication
spring.datasource.username=medi_user
spring.datasource.password=medi_pwd
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

