spring.application.name=medi-track

telegram.bot.username=@medi_track_bot

spring.datasource.url=jdbc:postgresql://localhost:5438/medication
spring.datasource.username=medi_user
spring.datasource.password=medi_pwd

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

telegram.bot.token=8844924028:AAGfiEGZHyClW5Bdjpwl8w_MJylL0AoCycs
